### ISSUE TITLE
Random lines appear when using `OrbitalCamera`

### ISSUE THREAD

**Issue by svilen-ivanov** [openrndr/openrndr#386] opened 2024-01-05 09:52 UTC
### Operating System

Linux

### OPENRNDR version

0.4.3 (using template)

### Java version (if applicable)

Azul 17

### Describe the bug

I'm trying to render a very basic scene, taken from Camera examples:
```kotlin
application {
    configure {
        width = 1920
        height = 1080
    }
    program {
        val camera = OrbitalCamera(
            Vector3.UNIT_Z * 90.0, Vector3.ZERO, 90.0, 0.1, 5000.0
        )
        val controls = OrbitalControls(camera, keySpeed = 10.0)

        extend(camera)
        extend(AxisHelper()) // shows XYZ axes as RGB lines
        extend(GridHelper()) // debug ground plane
        extend(controls) // adds both mouse and keyboard bindings
    }
}
```

It produces the following result:
![image](https://github.com/openrndr/openrndr/assets/829569/113305e2-d440-45c9-934a-f5aa97f955bc)

Notice the white lines that extend to infinity. Here is my version:

```
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic shared
 INFO [main] o.o.Application                 ↘ no preload class found 'org.openrndr.Preload'
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL vendor: AMD
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL renderer: AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.49, 6.2.0-39-generic)
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL version: 4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
```

Is it something I do wrong or perhaps it is a bug in my video card GL implementation?

Thank you!

**Comment by hamoid** [comment] 2024-01-05 10:13
Thanks for writing :-)

Is the issue still there if you switch to the `next-version` branch of the template?

**Comment by svilen-ivanov** [comment] 2024-01-05 11:14
I'm afraid it is reproducible with `next-version` too:
![image](https://github.com/openrndr/openrndr/assets/829569/6680a9fd-13a6-4369-b8f9-2b072cc3f34f)
![image](https://github.com/openrndr/openrndr/assets/829569/b9fd9456-4496-411c-9d02-c02505b810e7)

Using version `0.4.4-alpha7`

Forgot to mention: the issue doesn't occur every time, sometimes 2-3 consequent runs are fine but then it becomes broken again.

**Comment by svilen-ivanov** [comment] 2024-01-05 11:16
BTW, is there a way to force software rendering instead GPU-based?

**Comment by edwinRNDR** [comment] 2024-01-05 13:15
Hi @svilen-ivanov, I can't reproduce this is on my work system (nvidia + ubuntu based). I am guessing it is a driver user. Can you run your program using `-Dorg.openrndr.gl3.debug=true` and see if the driver reports problematic use of OpenGL? 

OPENRNDR uses OpenGL rendering only, you could try using llvmpipe to see if the problem persists.  The screenshots in orx are generated on github actions using an llvmpipe based OpenGL.

![image](https://github.com/openrndr/openrndr/assets/983309/093a34fe-449e-4e89-93a4-596baa69c1f6)

**Comment by svilen-ivanov** [comment] 2024-01-05 13:38
Thank you for looking into it. I don't see any change in the output when I added `-Dorg.openrndr.gl3.debug=true` (I also tried `-Dorg.openrndr.gl3.debug=TRUE` (uppercase `true`) found [here](https://guide.openrndr.org/advancedTopics/logging.html#enabling-opengl-debug-messages))

I lowered the log level to `TRACE` and here is the output: [application.log](https://github.com/openrndr/openrndr/files/13842649/application.log)

I'll read about `llvmpipe` more and will try it later.

**Comment by edwinRNDR** [comment] 2024-03-18 12:30
Closing as I think this is a configuration/driver issue. You are welcome to reopen the issue if this is not the case.

**Closed by edwinRNDR** 2024-03-18 12:30 UTC
Labels: bug
