### ISSUE TITLE
IllegalArgumentException when using ScreenRecorder

### ISSUE THREAD

**Issue by madhead** [openrndr/openrndr#24] opened 2018-10-12 14:30 UTC
**Describe the bug**
A program fails to start with an `IllegalArgumentException` when the app is extended with `ScreenRecorder` with some window sizes.

**To Reproduce**
Here is a small snippet of code:

```
class Demo : Program() {
    override fun setup() {
        extend(ScreenRecorder().apply {
            frameRate = 10
        })

        extend(FunctionDrawer {
            drawer.circle(width / 2.0, height / 2.0, 10.0)
        })
    }
}

fun main(args: Array<String>) {
    application(
            Demo(),
            configuration {
                width = 800
                height = 600
                showBeforeSetup = false
                hideCursor = true
            }
    )
}
```

If one starts it without modifications, the exception is given:

```
Exception in thread "main" java.lang.IllegalArgumentException: width (800) and height (599) should be divisible by 2
	at org.openrndr.ffmpeg.VideoWriter.size(VideoWriter.kt:150)
	at org.openrndr.ffmpeg.ScreenRecorder.setup(ScreenRecorder.kt:38)
	at org.openrndr.Program.extend(Program.kt:211)
	at Demo.setup(Posters.kt:9)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:434)
	at org.openrndr.Application$Companion.run(Application.kt:18)
	at org.openrndr.ApplicationKt.application(Application.kt:56)
	at PostersKt.main(Posters.kt:20)
```

To fix that one can set `height` to `601` or disable the `ScreenRecorder`.

**Expected behavior**
A black window with a small circle in a center

**Context:**
_OS_:

```
$ cat /etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.0-rc
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"
```
_OpenRNDR_:

```0.3.27```

_Java_:

```
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by edwinRNDR** [comment] 2018-10-13 12:56
Any idea what your context scaling factor is? I suspect it is fractional (like 1.5 or 2.5)?

**Comment by madhead** [comment] 2018-10-13 13:07
The `window.scale` property (inside a `Program` instance) is weird: Vector2(x=1.0, y=1.0026315450668335).

**Comment by madhead** [comment] 2018-10-13 13:19
This is what the debugger says:

```
val wcsx = FloatArray(1)  // wcsx[0] = 1.0
val wcsy = FloatArray(1)  // wcsy[0] = 1.0026315450668335

glfwGetWindowContentScale(window, wcsx, wcsy) // ← this line sets values above
```

**Comment by edwinRNDR** [comment] 2018-10-15 09:30
I suspect this is caused by something that is out of OPENRNDR's reach. You may want to test against some of the glfw examples in C and see if `glfwGetWindowContentScale` reports the same scale factors so we can report this as either a glfw or lwjgl bug. 

I am leaving the issue open for reference but I cannot resolve it as I don't have the means to reproduce the reported issue.

**Comment by clankill3r** [comment] 2019-07-31 09:00
Is `FunctionDrawer` from openrndr? I dont' have it.

**Comment by edwinRNDR** [comment] 2019-07-31 09:26
> Is `FunctionDrawer` from openrndr? I dont' have it.

Hi @clankill3r, `FunctionDrawer` was removed from the library as there's now an `extend` overload that takes a function directly.

**Comment by edwinRNDR** [comment] 2020-01-16 16:31
Closing this as it is getting old

**Closed by edwinRNDR** 2020-01-16 16:31 UTC
Labels: bug

**Comment by edwinRNDR** [comment] 2020-01-24 19:56
Ran into this problem again. It happens when the system dpi is set to something that is not a multiple of 96. It can be fixed by running `xrandr --dpi 96`, although I am not sure if this is the right solution.
